# Entity extraction

Read protocol `SECTION_CONTENT` nodes, pull design entities, and link each mention to a canonical `STANDARDIZED` entity shared across studies.

The chat model is an OpenAI-compatible LangChain connector. Set `LLM_API_KEY` and optional `LLM_BASE_URL`.

In [1]:
import sys
from pathlib import Path
root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

from src.extraction import build_chat_model, run_extraction, preview_extractions, sections_to_extract
model = build_chat_model()
print(type(model).__name__)
sample = sections_to_extract(per_study=1)[0]
print(sample["study_id"], sample["title"])

ChatOpenAI

NCT02099721 0 Eligibility Criteria

### Run the chain and show links

In [2]:

summary = run_extraction(model, per_study=8)
print(summary)
mentions, shared = preview_extractions(15)
display(mentions)
display(shared)

2026-09-28 14:11:48.068529

Prompt received at 14:11:48...

Response received at 14:11:52

2026-09-28 14:11:52.978045

Prompt received at 14:11:52...

Response received at 14:11:55

2026-09-28 14:11:55.284971

Prompt received at 14:11:55...

Response received at 14:11:56

2026-09-28 14:11:56.323562

Prompt received at 14:11:56...

Response received at 14:11:57

2026-09-28 14:11:57.477590

Prompt received at 14:11:57...

Response received at 14:11:58

2026-09-28 14:11:58.464935

Prompt received at 14:11:58...

Response received at 14:11:59

2026-09-28 14:11:59.589797

Prompt received at 14:11:59...

Response received at 14:12:00

2026-09-28 14:12:00.726432

Prompt received at 14:12:00...

Response received at 14:12:01

2026-09-28 14:12:01.869590

Prompt received at 14:12:01...

Response received at 14:12:02

2026-09-28 14:12:02.985547

Prompt received at 14:12:02...

Response received at 14:12:04

2026-09-28 14:12:04.063896

Prompt received at 14:12:04...

Response received at 14:12:05

2026-09-28 14:12:05.171249

Prompt received at 14:12:05...

Response received at 14:12:06

2026-09-28 14:12:06.224493

Prompt received at 14:12:06...

Response received at 14:12:07

2026-09-28 14:12:07.329987

Prompt received at 14:12:07...

Response received at 14:12:08

2026-09-28 14:12:08.395302

Prompt received at 14:12:08...

Response received at 14:12:09

2026-09-28 14:12:09.557690

Prompt received at 14:12:09...

Response received at 14:12:12

2026-09-28 14:12:12.898423

Prompt received at 14:12:12...

Response received at 14:12:15

2026-09-28 14:12:15.934632

Prompt received at 14:12:15...

Response received at 14:12:18

2026-09-28 14:12:18.310822

Prompt received at 14:12:18...

Response received at 14:12:24

2026-09-28 14:12:24.408748

Prompt received at 14:12:24...

Response received at 14:12:32

2026-09-28 14:12:33.105386

Prompt received at 14:12:33...

Response received at 14:12:38

2026-09-28 14:12:38.289023

Prompt received at 14:12:38...

Response received at 14:12:40

2026-09-28 14:12:40.663745

Prompt received at 14:12:40...

Response received at 14:12:45

2026-09-28 14:12:45.512720

Prompt received at 14:12:45...

Response received at 14:12:51

2026-09-28 14:12:51.312217

Prompt received at 14:12:51...

Response received at 14:12:54

2026-09-28 14:12:54.673432

Prompt received at 14:12:54...

Response received at 14:13:00

2026-09-28 14:13:00.431664

Prompt received at 14:13:00...

Response received at 14:13:04

2026-09-28 14:13:04.860643

Prompt received at 14:13:04...

Response received at 14:13:07

2026-09-28 14:13:07.442660

Prompt received at 14:13:07...

Response received at 14:13:12

2026-09-28 14:13:12.420443

Prompt received at 14:13:12...

Response received at 14:13:19

2026-09-28 14:13:19.663258

Prompt received at 14:13:19...

Response received at 14:13:24

2026-09-28 14:13:24.724914

Prompt received at 14:13:24...

Response received at 14:13:31

2026-09-28 14:13:32.222667

Prompt received at 14:13:32...

Response received at 14:13:39

2026-09-28 14:13:39.349242

Prompt received at 14:13:39...

Response received at 14:13:43

2026-09-28 14:13:43.469762

Prompt received at 14:13:43...

Response received at 14:13:46

2026-09-28 14:13:46.054244

Prompt received at 14:13:46...

Response received at 14:13:48

2026-09-28 14:13:48.433526

Prompt received at 14:13:48...

Response received at 14:13:49

2026-09-28 14:13:49.922861

Prompt received at 14:13:49...

Response received at 14:13:51

2026-09-28 14:13:51.632537

Prompt received at 14:13:51...

Response received at 14:13:56

2026-09-28 14:13:56.241613

Prompt received at 14:13:56...

Response received at 14:14:00

2026-09-28 14:14:00.832505

Prompt received at 14:14:00...

Response received at 14:14:04

2026-09-28 14:14:04.451268

Prompt received at 14:14:04...

Response received at 14:14:07

2026-09-28 14:14:07.234228

Prompt received at 14:14:07...

Response received at 14:14:09

2026-09-28 14:14:09.671091

Prompt received at 14:14:09...

Response received at 14:14:14

2026-09-28 14:14:14.880692

Prompt received at 14:14:14...

Response received at 14:14:17

2026-09-28 14:14:17.252764

Prompt received at 14:14:17...

Response received at 14:14:19

C:\Users\filipp03\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\bert\modeling_bert.py:413: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

{'sections': 46, 'mentions': 121, 'failures': 0, 'merged_canonical': 175}

,study_id,section,entity_type,span,canonical_name
0,NCT02099721,0 Eligibility Criteria,INCLUSION_CRITERION,Subject has a Class I indication for implantat...,Class I indication for ICD implantation
1,NCT02099721,0 Eligibility Criteria,INCLUSION_CRITERION,Subject (or subject's legally authorized repre...,Willingness to sign consent
2,NCT02099721,4 REGULATORY COMPLIANCE,INTERVENTION,"The Improve SCA study is a prospective, non-ra...",Improve SCA study
3,NCT02099721,4 REGULATORY COMPLIANCE,OBJECTIVE,The study will be conducted according to feder...,Compliance with local regulations
4,NCT02099721,4 REGULATORY COMPLIANCE,ASSESSMENT,The principles of the Declaration of Helsinki ...,Written informed consent
5,NCT02099721,8.1 Assessment Schedule,ASSESSMENT,Informed consent X,Written informed consent
6,NCT02099721,8 Visit schedule and assessments,ASSESSMENT,Informed consent X,Written informed consent
7,NCT02099721,4 REGULATORY COMPLIANCE,ASSESSMENT,MEC/IRB/HREC (all henceforth referred to as an...,Ethics Committee approval
8,NCT02099721,4 REGULATORY COMPLIANCE,ASSESSMENT,risk benefit assessment,Risk benefit assessment
9,NCT02099721,4 REGULATORY COMPLIANCE,ASSESSMENT,clinical trial registration,Clinical trial registration
10,NCT02099721,4 REGULATORY COMPLIANCE,ASSESSMENT,publication policy,Publication policy
11,NCT02099721,4 REGULATORY COMPLIANCE,ASSESSMENT,Approval of the CIP is required from the follo...,Approval of the CIP
12,NCT02099721,23 DEC 2013 Clinical Investigation Plan,OBJECTIVE,Improve SCA Programming Requirements,Improve SCA Programming Requirements
13,NCT02099721,23 DEC 2013 Clinical Investigation Plan,ENDPOINT,1.5 Prevention Mortality Endpoint,1.5 Prevention Mortality Endpoint
14,NCT02099721,23 DEC 2013 Clinical Investigation Plan,INTERVENTION,SCA Programming Requirements,SCA Programming

            entity_type               canonical_name  studies
0   INCLUSION_CRITERION         Age 5 years or older       13
1   EXCLUSION_CRITERION  Pregnancy and contraception       10
2   INCLUSION_CRITERION              Age requirement        8
3   INCLUSION_CRITERION     Written informed consent        7
4   INCLUSION_CRITERION  Pregnancy and contraception        5
5             OBJECTIVE      Assess long-term safety        5
6            ASSESSMENT             Laboratory tests        4
7          INTERVENTION                      Placebo        4
8            ASSESSMENT            Safety evaluation        4
9            ASSESSMENT         Physical examination        4
10             ENDPOINT               Adverse events        3
11           ASSESSMENT                  Vital Signs        3
12           ASSESSMENT       Monitor adverse events        3
13           ASSESSMENT                  12-Lead ECG        3
14           ASSESSMENT     Written informed consent        3