# Load the public corpus

Connect to the existing Neo4j server and load the ClinicalTrials.gov studies stored in `corpus/`.

In [1]:
import sys
from pathlib import Path
root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

from src.loader import load_corpus
from src.similarity import graph_summary, study_preview, protocol_studies, protocol_csr_studies
summary = load_corpus()
print(graph_summary())
display(study_preview())

[public-ctg] Total nodes: 4446, Total relationships: 6068

,study_title,comparative_study,subject_type,study_phase,study_status
0,"MERIT-2 : Long Term, Multicenter, Single-arm, ...",N,PATIENTS,PHASE2,COMPLETED
1,Improve Sudden Cardiac Arrest Study,N,PATIENTS,NA,COMPLETED
2,Fixed Dose Intervention Trial of New England E...,Y,PATIENTS,PHASE4,COMPLETED
3,Improving Advanced Cancer Patient-Centered Car...,Y,PATIENTS,NA,COMPLETED
4,"An Open Label, Multicenter Study to Assess the...",N,PATIENTS,PHASE4,COMPLETED

### Document coverage

In [2]:

print("Studies with a protocol")
display(protocol_studies())
print("Studies with a protocol and a CSR")
display(protocol_csr_studies())

Studies with a protocol

     study_name                                study_node_id
0   NCT02060721  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:5717
1   NCT02099721    4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:80
2   NCT02188121   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:284
3   NCT02374255   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:453
4   NCT02427958   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:473
5   NCT02505984   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:675
6   NCT02528357   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:744
7   NCT02564926   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:993
8   NCT02709655  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1164
9   NCT02713867  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1414
10  NCT02725515  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1661
11  NCT02752048  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1886
12  NCT02761993  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2091
13  NCT02855125  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2317
14  NCT02879578  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2562
15  NCT03194776  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2793
16  NCT03224130  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3003
17  NCT03436784  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3086
18  NCT03461016  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3119
19  NCT03542149  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3132
20  NCT03579433  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3248
21  NCT03635099  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3444
22  NCT03743038  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3694
23  NCT04246593  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3911
24  NCT04321252  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:4093

Studies with a protocol and a CSR

     study_name                                study_node_id
0   NCT02060721  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:5717
1   NCT02099721    4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:80
2   NCT02188121   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:284
3   NCT02374255   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:453
4   NCT02427958   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:473
5   NCT02505984   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:675
6   NCT02528357   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:744
7   NCT02564926   4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:993
8   NCT02709655  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1164
9   NCT02713867  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1414
10  NCT02725515  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1661
11  NCT02752048  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:1886
12  NCT02761993  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2091
13  NCT02855125  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2317
14  NCT02879578  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2562
15  NCT03194776  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:2793
16  NCT03224130  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3003
17  NCT03542149  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3132
18  NCT03579433  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3248
19  NCT03635099  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3444
20  NCT03743038  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3694
21  NCT04246593  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:3911
22  NCT04321252  4:3cf6aee3-b618-46ae-9144-2e0d3ee5ddf7:4093